language: node_js
sudo: false
node_js:
  - 9
install:
  - cd backoffice && npm install && npx eslint . && cd .. && docker-compose up -d mongodb && cd frontoffice && npm install && ng test
script:
  - npm test
